#!/bin/bash

parent_path=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )

echo "Testing version $VERSION"
$parent_path/../deploy/k8_deploy

sleep 1

HELLO_IP=$(kubectl get services/hello -o json | jq -r '.status.loadBalancer.ingress[].ip')
HELLO_HOST=$(kubectl get services/hello -o json | jq -r '.status.loadBalancer.ingress[].hostname')

HELLO_URL="http://$HELLO_IP"
if [[ "$HELLO_IP" = "null" ]]; then
  HELLO_URL="http://$HELLO_HOST"
fi

# TEST GET
result=$(curl -s $HELLO_URL)
if [[ $result == "Hello world!" ]]; then
  echo GET: PASS
else
  echo GET: FAIL
fi

# TEST POST
result=$(curl -s -X POST --data "Testy McTestface" $HELLO_URL)
if [[ $result == "Hello Testy McTestface world!" ]]; then
  echo POST: PASS
else
  echo POST: FAIL
fi
