#!/bin/bash

parent_path=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )

echo "Testing version $VERSION"
$parent_path/../deploy/k8_deploy

HELLO_IP=$(kubectl get services/hello -o json | jq -r '.status.loadBalancer.ingress[].ip')

# TEST GET
result=$(curl -s http://$HELLO_IP)
if [[ $result == "Hello world!" ]]; then
  echo GET: PASS
else
  echo GET: FAIL
fi

# TEST POST
result=$(curl -s -X POST --data "Testy McTestface" http://$HELLO_IP)
if [[ $result == "Hello Testy McTestface world!" ]]; then
  echo POST: PASS
else
  echo POST: FAIL
fi
