#!/bin/bash

echo "Testing version $VERSION"

docker run --name test -p 80:80 -d $IMAGE:$VERSION 2>&1 > /dev/null

sleep 1

# Test GET
result=$(curl -s http://localhost)
if [[ $result == "Hello world!" ]]; then
  echo GET: PASS
else
  echo GET: FAIL
fi

# Test POST
result=$(curl -s -X POST --data "Warren" http://localhost)
if [[ $result == "Hello Warren world!" ]]; then
  echo POST: PASS
else
  echo POST: FAIL
fi

docker stop test 2>&1 > /dev/null
docker rm test 2>&1 > /dev/null
