apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.environment }}-{{ .Values.name }}"
  labels:
    app: "{{ .Values.environment }}-{{ .Values.name }}"
spec:
  ports:
  - name: http
    port: {{ .Values.port }}
    targetPort: {{ .Values.targetPort }}
  selector:
    app: "{{ .Values.environment }}-{{ .Values.name }}"
