apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello
spec:
  replicas: 4
  template:
    metadata:
      labels:
        run: hello
    spec:
      containers:
      - name: hello
        image: {{ registry }}/{{ image }}:{{ version }}
        ports:
        - containerPort: 80
